const SOCKET_MAX_PAYLOAD = 1000000;
const MATCH_DETAILS = 'User match details';

const DB_CONNECTION_TIMEOUT_MILLIS = 2000;
const DB_MAX_CLIENTS = 20;
const DB_IDLE_TIMEOUT_MILLIS = 30000;

export {
   MATCH_DETAILS, SOCKET_MAX_PAYLOAD, DB_CONNECTION_TIMEOUT_MILLIS, DB_MAX_CLIENTS, DB_IDLE_TIMEOUT_MILLIS
}