const SOCKET_MAX_PAYLOAD = 1000000;

const MATCH_DETAILS = 'User match details';
const CHECK_USER_MATCHED_KEY = 'match:userId:';

const DB_CONNECTION_TIMEOUT_MILLIS = 10000;
const DB_MAX_CLIENTS = 20;
const DB_IDLE_TIMEOUT_MILLIS = 30000;

const CHAT_SOCKET_PATH = '/v1/match/chat-socket';

export {
    MATCH_DETAILS, SOCKET_MAX_PAYLOAD, DB_CONNECTION_TIMEOUT_MILLIS, DB_MAX_CLIENTS, DB_IDLE_TIMEOUT_MILLIS, 
    CHECK_USER_MATCHED_KEY, CHAT_SOCKET_PATH
}